### PR TITLE
Update for maven plugin

### PR DESCRIPTION
**Pull request by AlexBelchUK**

### CODE REVIEW

**Comment by salmonb** [comment]
Thanks Alex for this PR, that's very helpful that you created the initial structure of the project, as I never wrote a Maven plugin before 👍

I haven't told you the precise goal I have in mind for that Maven plugin, so I need to explain it to you now. The goal of this plugin is not be able to invoke any possible command of the WebFX CLI from Maven (I think people can just use the CLI directly for that), but to call a specific feature during the Maven build (this feature may even not be directly accessible from the command line, but just exposed separately for the Maven plugin).

The context is reusable webfx libraries (such as WebFX Platform, WebFX Extras, etc...) and reusable webfx projects (such as Modality), which are composed of many modules, with many webfx.xml files. To simplify the import of these modules in their projects, developers just need to write this in their webfx.xml:

```xml
    <required-libraries>
        <webfx-library artifact="dev.webfx:webfx-extras:0.1.0-SNAPSHOT"/>
    </required-libraries>
```

or 

```xml
    <required-libraries>
        <webfx-library artifact="one.modality:modality:1.0.0-SNAPSHOT"/>
    </required-libraries>
```
and that's enough for the WebFX CLI to immediately become aware of all the underlying modules, because the root webfx.xml of such reusable webfx projects is a bit special and contains some extra information about children modules in a xml tag called `<export-snapshot>`. For example, you can have a look at the root [webfx.xml](https://github.com/modalityone/modality/blob/main/webfx.xml) of Modality, and you will see that tag.

Right now `<export-snapshot>` is generated during `webfx update` which recognises such projects thanks to the presence of this in the root webfx.xml:

```xml
    <update-options>
        <generate-export-snapshot/>
    </update-options>
```
and finally this webfx.xml file is published to the Maven repository, therefore available for other developers via the WebFX CLI that downloads it for all `<webfx-library>` listed in `<required-libraries>`.

This works already right now without the Maven plugin, but the developer of the reusable library/project needs to remember to always run a `webfx update` before releasing a new version or snapshot to refresh that `<export-snapshot>`, and if he forgets, this will result in outdated information published to the Maven repository. So it would be much better if that process was automatically done during the Maven build, and this is the actual purpose of the WebFX Maven plugin.

Right now, all webfx.xml files are automatically transformed into Maven artifacts during the package phase (and eventually published later during the install/deploy phase) thanks to that profile in the parent-webfx [pom.xml](https://github.com/webfx-project/webfx-parent/blob/main/pom.xml) that is automatically activated each time a webfx.xml file is detected: 

```xml
       <!-- Automatically attach webfx.xml (if present) to the artifact in its Maven repository -->
        <profile>
            <id>auto-attach-webfx-xml</id>
            <activation>
                <file>
                    <exists>webfx.xml</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <!-- Using the build helper plugin to attach webfx.xml -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>${plugin.buildhelper.version}</version>
                        <executions>
                            <execution>
                                <id>attach-webfx-xml</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>attach-artifact</goal>
                                </goals>
                                <configuration>
                                    <artifacts>
                                        <artifact>
                                            <file>webfx.xml</file>
                                            <type>xml</type>
                                            <classifier>webfx</classifier>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
So I would like the WebFX Maven plugin to be called at this point for reusable webfx libraries/projects. Ideally, the root webfx.xml 'source' (controlled by git) should not contain `<export-snapshot>` (as opposed to what's happening now). This tag should be dynamically generated and added only to the webfx.xml 'destination' (the Maven artifact).

How do you think we can achieve this? Should we replace the `build-helper-maven-plugin` with our own plugin that will transform the webfx.xml 'source' to 'destination' and finally pass it to `build-helper-maven-plugin`?

**Comment by AlexBelchUK** [comment]
From the above I think that the new webfx plugin would need to run at the prepare-package
build phase, before the packaging is done, I've added an example below of what I think can be done,
basically adding the new plugin and attaching it to the prepare-package build phase.
(https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html gives a list of phases to attach to)
I've added CLI pseudo arguments as I don't know what the specifics would be... 

 
        <profile>
            <id>auto-attach-webfx-xml</id>
            <activation>
                <file>
                    <exists>webfx.xml</exists>
                </file>
            </activation>
            <build>
                <plugins>

                    
                    <plugin> 
                        <groupId>dev.webfx</groupId>
                        <artifactId>webfx-maven-plugin</artifactId>
                        <version>0.1.0-SNAPSHOT</version>
                        <executions>
                            <execution>
                                <id>update-webfx-xml</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>cli</goal>
                                </goals>
                            </execution>
                      </executions>
                      <configuration>
                          <args>
                              <arg>new_update_command</arg>
                              <arg>new_update_command_options</arg>
                          </args>
                          <failOnError>true</failOnError>
                       </configuration>
                    </plugin>

                    
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>${plugin.buildhelper.version}</version>
                        <executions>
                            <execution>
                                <id>attach-webfx-xml</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>attach-artifact</goal>
                                </goals>
                                <configuration>
                                    <artifacts>
                                        <artifact>
                                            <file>webfx.xml</file>
                                            <type>xml</type>
                                            <classifier>webfx</classifier>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

**Comment by salmonb** [comment]
Thanks Alex for clarifying the Maven prepare-package phase, and your proposition makes sense.

I think we can rename the goal from `cli` to `export` to better express what the WebFX Maven plugin does. I can prepare a specific export() entry point in the WebFX CLI that the Maven plugin will call. It will find the webfx.xml 'source', and generate the webfx.wml 'destination' (with the `<export-snapshot>` added for reusable libraries/projects). Any idea how the webfx.xml 'destination' can be passed to `build-helper-maven-plugin` without overwriting the webfx.xml 'source'?

**Comment by AlexBelchUK** [comment]
I see that the maven-build-helper-plugin uses the attach artifact goal to add files to the build.
In the artifacts section I wonder if the path could be set on the file attribute. 
 <artifacts>
     <artifact>
            <file>/some/new/path/webfx.xml</file>
            <type>xml</type>
           <classifier>webfx</classifier>
       </artifact>
   </artifacts>

Possibly another way would be to move the current file, when running export() 
then perform a build-helper-maven-plugin package as now and then add another
webfx-plugin goal to restore() the file and attach to a build phase after the package phase - 
possibly depending on plug in run order - 'package' or if the webfx-maven-plugin runs 
after the maven-build-helper-plugin the 'install' phase.

Those are what I can think of, sorry, I lack knowledge in this area too

**Comment by salmonb** [comment]
Thanks, I will try to put the webfx.xml 'destination' somewhere in the target folder and give that path the `build-helper-maven-plugin` as you suggested, I think this should work. I didn't have time to try that today, but will do tomorrow, and if it works, I will give you the new entry point in the WebFX CLI to be used for the Maven plugin.

**Comment by salmonb** [comment]
I added the `dev.webfx.cli.mavenplugin.Export` class to the WebFX CLI. It has a method `public static int export(String projectDirectory, String targetDirectory)`.

So the next steps should be:

- replace the call to the update command with a call to `Export.export()`
- make the plugin evaluate  `${basedir}` and pass this value as `projectDirectory`
- make the plugin evaluate `${project.build.directory}` and pass this value as `targetDirectory`
- remove the `args` parameter
- rename the goal from `cli` to `export`

Can you please do these changes?

Once done, I will try using the plugin in the `auto-attach-webfx-xml` profile! 😀

**Comment by AlexBelchUK** [comment]
Okay I'll try to pick that up in the next day or so, then all will be good to go.

**Comment by salmonb** [comment]
Great, it works! 🥳

Just a couple of minor improvements: could you set the Maven default value for `projectDirectory` and `targetDirectory` parameters to be `${basedir}` and `${project.build.directory}` respectively, so we don't need to fill them well calling the plugin? (there is no reason for another value)

And the last thing I would like to investigate is the possibility to remove the `build-helper-maven-plugin` by just doing what it does directly in our plugin. I found the source of the [AttachArtifactMojo](https://github.com/mojohaus/build-helper-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/buildhelper/AttachArtifactMojo.java) and basically what does the trick is a call to `projectHelper.attachArtifact()`. So could you try to execute this when the CLI export is successful?

```java
projectHelper.attachArtifact(project, "xml", "webfx", new File(new File(targetDirectory), "webfx-artifact/webfx.xml"));
```

You will need to get the `projectHelper` and `project` objects from Maven, but you can have a look at their code to see how it's done.

Thank you!

**Comment by AlexBelchUK** [comment]
Code has now been updated to include projectHelper and project injection but at cost of removing the
module file due to a package / module clash which I could not resolve.

**Comment by salmonb** [comment]
Amazing, it's working now without the need of `build-helper-maven-plugin`! 🥳 Well done!

No pb for the module-info.java removal, funny that Maven itself is not compatible with the Java module system, must be a legacy thing...

Last little thing before I merge this PR: can you please rename the class to ExportMojo? It looks like it's the standard way of naming.

Thank you!

**Comment by salmonb** [comment]
Also I think the logs can be for debug only, not info. Thanks!

**Comment by AlexBelchUK** [comment]
Changes pushed :-)

**Pull request merged**
